@startuml
set separator none
title Payment Gateway - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(PaymentApplication, "Payment Application", $descr="Application integrates Payments Platform for payments processing", $tags="", $link="")
System(PaymentNetwork, "Payment Network", $descr="", $tags="", $link="")

System_Boundary("PaymentGateway_boundary", "Payment Gateway", $tags="") {
  Container(PaymentGateway.SettlementAPI, "Settlement API", $techn="", $descr="Settlement Payment", $tags="", $link="")
  Container(PaymentGateway.PaymentEventsStream, "Payment Events Stream", $techn="", $descr="Event Stream for Payment", $tags="", $link="")
  ContainerDb(PaymentGateway.Cache, "Cache", $techn="", $descr="Cache Layer for Payment", $tags="", $link="")
  Container(PaymentGateway.RoutingAPI, "Routing API", $techn="", $descr="Routing Payment", $tags="", $link="")
  Container(PaymentGateway.FraudDetection, "Fraud Detection", $techn="", $descr="Fraud Detection for Payment", $tags="", $link="")
  Container(PaymentGateway.SSO, "SSO", $techn="", $descr="Single Sign On", $tags="", $link="")
  Container(PaymentGateway.AIService, "AI Service", $techn="", $descr="AI Service for Fraud Detection", $tags="", $link="")
  ContainerDb(PaymentGateway.LedgerDB, "Ledger DB", $techn="", $descr="Ledger Database", $tags="", $link="")
  Container(PaymentGateway.PaymentsAPI, "Payments API", $techn="", $descr="Provide payments capabilities for consumers", $tags="", $link="")
  Container(PaymentGateway.ValidationAPI, "Validation API", $techn="", $descr="Validate Payment", $tags="", $link="")
  Container(PaymentGateway.ClearingAPI, "Clearing API", $techn="", $descr="Clearing Payment", $tags="", $link="")
}

Rel(PaymentGateway.PaymentsAPI, PaymentGateway.SSO, "Authenticate and authorize request", $techn="", $tags="", $link="")
Rel(PaymentGateway.PaymentsAPI, PaymentGateway.PaymentEventsStream, "Listen on Payment Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.RoutingAPI, PaymentGateway.PaymentEventsStream, "Listen on Payment Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.FraudDetection, PaymentGateway.PaymentEventsStream, "Listen on Payment Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.ClearingAPI, PaymentGateway.PaymentEventsStream, "Listen on Payment Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.SettlementAPI, PaymentGateway.PaymentEventsStream, "Listen on Settlement Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.ValidationAPI, PaymentGateway.PaymentEventsStream, "Listen on Payment Events", $techn="", $tags="", $link="")
Rel(PaymentGateway.FraudDetection, PaymentGateway.Cache, "Cache", $techn="", $tags="", $link="")
Rel(PaymentGateway.FraudDetection, PaymentGateway.AIService, "Score transaction", $techn="", $tags="", $link="")
Rel(PaymentGateway.SettlementAPI, PaymentGateway.LedgerDB, "Read transactions", $techn="", $tags="", $link="")
Rel(PaymentGateway.RoutingAPI, PaymentGateway.LedgerDB, "Save transactions", $techn="", $tags="", $link="")
Rel(PaymentApplication, PaymentGateway.PaymentsAPI, "Process payment", $techn="", $tags="", $link="")
Rel(PaymentGateway.RoutingAPI, PaymentNetwork, "Send transaction", $techn="", $tags="", $link="")
Rel(PaymentGateway.SettlementAPI, PaymentNetwork, "Send batch transactions", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml