name: Build and Deploy

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  deploy_github_pages:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: |
        brew tap avisi-cloud/tools
        brew install structurizr-site-generatr

    - name: Build the site
      run: structurizr-site-generatr generate-site -w architecture-repository/payments-platform/workspace.dsl -a assets --branches main --default-branch main

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/site
        clean: true
